# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Haraesh Jayasethu Ramachandran
email: haraesh.jr@gmail.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  haraeshverse
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: haraesh-j-071195
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: hj_lostintheinternet3754
# googleplus_username: +jekyll
orcid_username: 0009-0004-9947-5790

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-picture.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! My name's Haraesh. (Pronounced as ha-ray-sh). Currently, I am pursuing a PhD in edge computing, industrial IoT and networking. I have 4 years of work experience as a developer in the information technology industry, under the pension and education domains. I also have 9 months of research experience in IoT and Fog computing.

content:
  - title: PhD in Computer Science
    layout: list
    content:
      - layout: left
        title: Latency-driven container network optimization in systems integrating Edge computing and industrial IoT
        caption: 2025 - 2028 (expected)
        sub_title: With the MAGELLAN team, IRISA, University of Rennes, Rennes, France
        description: | # this will include new lines to allow paragraphs
          My PhD is on the topic of edge computing and industrial IoT and networking, particularly latency in these systems. If you want to discuss more about my thesis, please contact me by email, or the MAGELLAN team directly!    
  
  - title: Academic Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Rennes, Rennes, France
        caption: 2023 - 2025
        sub_title: Masters in Cloud and Network Infrastructures
        description: | # this will include new lines to allow paragraphs
          - Specialized Master's in Cloud Computing and networking, with other subjects such as advanced programming for research, Big Data infrastructures, IoT, Fog and Edge computing
          - Minor in innovation and entrepreneurship with subjects such as business trends in tech, social responsibility, institutional change and entrepreneurship, conducted by EIT Digital
          - *Studied/Used:* AWS, R/Java for human motion detection, Cloud technologies (Kubernetes, Grafana, InfluxDB, node-red, Docker)
      
      - layout: left
        title: Madurai Kamaraj University, Madurai, India
        caption: 2016 - 2019
        sub_title: Masters in Computer Applications (MCA)
        description: | # this will include new lines to allow paragraphs
          - *Studied subjects such as:* Web development, Cloud computing, mobile computing, software engineering, networking
          - Also studied minors such as: aquarium management and ornamental fish culture, photography, French

      - layout: left
        title: The Madura College, Madurai, India
        caption: 2013 - 2016
        sub_title: BSc Computer Science
        description: | # this will include new lines to allow paragraphs
          - *Studied subjects such as:* Web programming, database management, networking, software engineering
          - Also studied minors such as: accounting, environmental studies


  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Institut de Recherche en Informatique et Systèmes Aléatoires (IRISA)
        sub_title: Research and Development Intern
        caption: February 2025 - July 2025
        description: | # this will include new lines to allow paragraphs
          - Worked with the Magellan team in researching the utilization of Fog computing in the context of environmental data processing using IoT
          - Developed prototype applications and structure to be integrated into a Fog system to aid with environmental data processing using Python and Docker
          - Developed a workload injector to inject a dataset into a Fog computing platform, to observe its performance when overloaded
          - This internship was done as part of the requirements for my Masters in Cloud and Network Infrastructures

      - layout: left
        title: Institut de Recherche en Informatique et Systèmes Aléatoires (IRISA)
        sub_title: Research and Development Intern
        caption: June 2024 - August 2024
        description: | # this will include new lines to allow paragraphs
          - Worked with the Ermine team in researching pest propagation detection in agricultural fields with a network using a combination of IoT and satellite communication
          - Studied NS3 and LR-FHSS-Sim to try to simulate a network connecting sensors using LR-FHSS/LoRa
          - Aimed to integrate NS3 with satellite and LoRa communication packages to provide a simulation environment
          - Attempted to integrate LR-FHSS with the physical layer in aforementioned simulation environment
          - Studied existing research being done in related domain to provide a state-of-the-art report

  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Finalsite (Acquired from Blackboard K-12)
        sub_title: Associate Software Engineer
        caption: November 2021 - August 2023
        description: | # this will include new lines to allow paragraphs
          - Worked in the development and maintenance of Web application focusing on community engagement between schools and parents in a Scaled Agile environment
          - Improved automated testing, accessibility, UI/UX design, security of the application
          - Participated in data migration activities between one application to another
          - Conducted research activities for more than 3 epics to improve quality of application
          - Resolved issues arising from testing, pre-production and post-production phases of application maintenance in a short time interval
          - Coordinated with DevOps teams for deployment and release, routine maintenance activities
          - *Used:* Web development technologies (HTML/CSS/JS/jQuery), .NET MVC/C#, SQL Server, AWS ECR/ECS, Selenium, Burp Suite Community Edition, aXe DevTools

      - layout: left
        title: Sagitec Software Solutions Inc.
        # link_text: boringcompany.com
        sub_title: (Associate) Software Engineer
        caption: August 2019 - November 2021
        description: | # this will include new lines to allow paragraphs
          - Part of development of a Web application for processing pension-related data
          - Developed 11+ functionalities to be integrated into the application
          - Coordinated with business analysts and clients to improve and reinforce documentation and design specifications of the application
          - Resolved issues arising from 3 different layers of testing in a short time interval
          - *Used:* Web development technologies (HTML/CSS/JS/jQuery), Sagitec Neospin, .NET MVVM/C#, Oracle SQL
      
      - layout: left
        title: Gympik (now Roundglass Gympik)
        # link_text: boringcompany.com
        sub_title: Web Development Intern
        caption: February 2019 - April 2019
        description: | # this will include new lines to allow paragraphs
          - Developed a prototype for a social media page to be integrated with a Web development CRM for fitness organizations, potentially to be used for marketing
          - Studied existing applications/plugins which could be used before developing prototype
          - *Used:* Web development technologies (HTML/CSS/JS/jQuery), Laravel, PHP, MySQL, Vue.js, Facebook Graph, Twitter/X integration
            
  - title: Certificates # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        description: | # this will include new lines to allow paragraphs
          - Front End Development Libraries, freeCodeCamp: <a href="https://www.freecodecamp.org/certification/haraesh0711/front-end-development-libraries">(2023)</a>
          - Responsive Web Design, freeCodeCamp: <a href="https://www.freecodecamp.org/certification/haraesh0711/responsive-web-design">(2018)</a>
          - JavaScript Algorithms and Data Structures, freeCodeCamp: <a href="https://www.freecodecamp.org/certification/haraesh0711/javascript-algorithms-and-data-structures">(2018)</a>
          - Indigenous Canada, University of Alberta, Coursera: <a href="https://www.coursera.org/account/accomplishments/verify/Q8TXXRYT2KNM">(2022)</a>

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: CodePen profile
        link: https://codepen.io/haraeshjr
        description: | # this will include new lines to allow paragraphs
          As part of my freeCodeCamp certifications, I developed several (small) Web applications (that I now look at with severe judgment). You can find them in my CodePen profile.  

# Footer
footer_show_references: true
references_title: Website template adapted from the wonderful work done <a href = "https://github.com/sproogen/modern-resume-theme" target="_blank">here.</a>

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
